# Generated by Django 3.2 on 2021-05-13 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCreationForm',
        ),
    ]
