# Generated by Django 3.2 on 2021-05-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('healthapp', '0002_delete_usercreationform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('Postal Code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('hospitalname', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('Medicinename', models.CharField(max_length=100)),
                ('mobilenumber', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('Postal Code', models.CharField(max_length=100)),
            ],
        ),
    ]
