# Generated by Django 3.2 on 2021-05-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0004_medicine_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diseases_name', models.CharField(max_length=100)),
                ('medicine_prescribed', models.CharField(max_length=100)),
                ('cause_of_the_disease', models.CharField(max_length=100)),
                ('affected_people_number', models.IntegerField()),
                ('Specialist_doctor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('hospital_currently_working', models.CharField(max_length=100)),
                ('languages_known', models.IntegerField()),
                ('specilization', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
