# Generated by Django 3.2 on 2021-05-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0005_diseases_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_on_card', models.CharField(max_length=100)),
                ('Credit_card_number', models.CharField(max_length=20)),
                ('Exp_Month', models.CharField(max_length=20)),
                ('Exp_Year', models.CharField(max_length=4)),
                ('CVV', models.CharField(max_length=4)),
                ('Amount_to_be_paid', models.CharField(max_length=5)),
            ],
        ),
    ]
