# Generated by Django 3.2 on 2021-05-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0007_alter_pay_amount_to_be_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='Amount_to_be_paid',
            field=models.CharField(default='500', max_length=3),
        ),
    ]
