# Generated by Django 4.0.3 on 2022-03-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0009_rename_postal code_medicine_postalcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=100)),
                ('contact_message', models.TextField(blank=True)),
            ],
        ),
    ]
